### ISSUE TITLE
Device Bootlogos

### ISSUE THREAD

**Issue by nnn19** [rubencarneiro/rubencarneiro.io#1]
The developed Bootlogos are well designed and I gave a try on my UT Device.

The imgdata in LG Nexus 4 gave the following error while
fastboot flash imgdata imgdata.img

sending 'imgdata' (2140 KB)...
OKAY [  0.069s]
writing 'imgdata'...
FAILED (remote: partition table doesn't exist)
finished. total time: 0.071s

Thanks in advance.

@NatarajanNNapoleon

**Comment by rubencarneiro** [comment]
yeah theres no Nexus 4 on the webpage.

**Comment by rubencarneiro** [comment]
so you are flashing nexus 5 bootlogo on nexus 4

**Comment by nnn19** [comment]
Thanks for the reply.

I hope the Nexus 5 Image can be used for Nexus 4 and there will be a change in procedure. Is it right? What can I do for Nexus 4?

Thanks in advance.
